---
title: "Examples with Leaflets"
author: "Daniel Kaplan (modified by Nicholas Horton)"
date: "June 14, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(leaflet)
require(sp)
require(maps)
```
# A simple map

```{r}
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lat=40.7566, lng=-73.9863, popup="Times Square")
m  # Print the map
```

# Another simple map

```{r}
mapStates <- map("state", fill = TRUE, plot = FALSE)
leaflet(data = mapStates) %>% 
  addTiles() %>%
  addPolygons(fillColor = topo.colors(10, alpha = NULL), stroke = FALSE)
```

# Simple annotations

```{r}
m <- leaflet() %>% 
  addTiles()
df <- data.frame(
  lat = rnorm(100),
  lng = rnorm(100),
  size = runif(100, 5, 20),
  color = sample(colors(), 100)
)
m <- leaflet(df) %>% 
  addTiles()
m %>% 
  addCircleMarkers(radius = ~size, color = ~color, fill = FALSE)
m %>% 
  addCircleMarkers(radius = runif(100, 4, 10), color = c('red'))
```

# Street maps

```{r}
m <- leaflet() %>% 
  setView(lng = -71.0589, lat = 42.3601, zoom = 12)
m %>% 
  addTiles() 
```

```{r}
m %>% 
  addProviderTiles("CartoDB.Positron")
```

* Adding layers

```{r}
leaflet() %>% 
  addTiles() %>% 
  setView(-93.65, 42.0285, zoom = 4) %>%
  addWMSTiles(
    "http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi",
    layers = "nexrad-n0r-900913",
    options = WMSTileOptions(format = "image/png", transparent = TRUE),
    attribution = "Weather data © 2012 IEM Nexrad"
  )

```

