---
title: "Working Schedule"

output: 
  html_document:
    template: null
    css: ../stylesheets/cvc.css
    
---


<script src="../javascripts/main.js"></script>
<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

<div class="wrapper">
<nav>
<ul></ul>
</nav>
<section>
     
           
<header>
<h1>CVC 2017 Working Schedule</h1>
<p>Computation and Visualization Consortium</p>
</header> 

This is cvc.mosaic-web.org/Summer2017/schedule2017.html

## Resources

  * [CRAN](http://cran.r-project.org) (Comprehensive R Archive Network) has lots of R-related stuff
  * The `mosaic` package (version 0.14.4 or greater) and its vignettes are [available via CRAN](http://cran.r-project.org/web/packages/mosaic/index.html) and also via [github](https://github.com/ProjectMOSAIC/mosaic)
  * [The Calvin College RStudio server](http://rstudio.calvin.edu) has provided accounts for all workshop participants.
    * [Change passwords here](https://freeipa1.cs.calvin.edu/)
  * Slides and files for sessions will be posted in the schedule as we go along (see below).


## Provide Feedback

We'll use this Google Doc to record your questions and comments and to provide
responses.  Feel free to edit it at anytime before, during, or (shortly) after the workshop.

  * [Google Doc](https://docs.google.com/document/d/1AtoWauyDoBsHJd7yywkJNgiNaAXPiBjNhqO9Yw72jys/edit?usp=sharing)

## Project ideas and updates

We'll use this Google Doc to share information about project ideas and updates.

  * [Google Doc](https://docs.google.com/document/d/1ScLIjBWD12P28WbluL6L5Shzh0mLL2V1N9Zm0Z1ljj8/edit?usp=sharing)

## Working Schedule

This schedule will be updated throughout the workshop.  All items should be 
considered tentative until they happen since we will adjust things to 
meet the needs and wishes of the participants.

### Sunday

Arrival day for many coming from out of town. 

 
  * Details TBA

### Monday

 1. Welcome (9am)
    a. Welcome to CVC/Macalester [Danny]
    b. [Goals and outline for the week](Intro/IntroOverview.html) [Randy]

 2. Introductions [Randy]
    a. **Activity**: Split up into groups of three or four and introduce yourselves. 
    b. [Google Doc](https://docs.google.com/document/d/17JBw6KW-i5hJffL96kiRTxTjlJFW2qGBrl1g9Ixgb4I/edit#) for second part. 

 3. A First Case Study using Medicare Data 
 
    a. [Thinking with data](http://amstat.tandfonline.com/doi/full/10.1080/00031305.2015.1094283) [Nick]
    
    b. [Curriculum Guidelines for Data Science](http://www.annualreviews.org/doi/abs/10.1146/annurev-statistics-060116-053930) [Nick]

    b. [Slides](Intro/MedicareSpending.html) [Danny]

 4. Introduction to R and R Studio [Randy]

    * [Less Volume, More Creativity -- An R Quick Start](Learn/LessVolume/LessVolume.html) 
    
    * [US Births Tutorial](https://dtkaplan.shinyapps.io/USBirths/)
        - More details on `ggformula`: [a longer tutorial](http://dtkaplan.shinyapps.io/Plotting_with_formulas) & [refining graphics](http://dtkaplan.shinyapps.io/Refining_ggformula)
    
    * Orientation to RStudio: Panes & tabs
    
    * Importing CSV and Excel files into RStudio
        * [Notes](Learn/ImportingData/ImportingData.html)
        * [Anscombe.csv](Learn/ImportingData/Anscombe.csv)
    
    * **Activity**: Create a plot using data that you have imported into R.

 5. [RMarkdown](http://prezi.com/vq6l5yqpnqma/) [Nick]
 
    a. Creating PDF/HTML/Word documents in RStudio
    b. [TISE paper by Baumer *et al*](http://escholarship.org/uc/item/90b2f5xh)
    c. [RMarkdown cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
    d. Example: [R Markdown example](https://rawgit.com/dtkaplan/CVC/gh-pages/Summer2017/Learn/RMarkdown/student-evals.Rmd); [R Markdown formatted](Learn/RMarkdown/student-evals.pdf) (Student evaluations example from Open Intro)

    e. **Activity**: Write and publish a description of some 
    straightforward, data-oriented topic you'd like to present in class. 
        * Include at least 1 plot (even if unrelated) to make sure 
        you know how to do that.  
        * Use the mosaic `fancy` html template as a starting point
        
 6. How to organize your data [Danny]
    
    a. [**Introduction slides**](Learn/TidyData/tidy_data.html), but the basics are
    
      * Rectangular format: cases (rows) and variables (columns)
      * Separate your analysis from data storage.
      * Use a codebook to describe your cases and variables in detail.
       
    b. **Activity**: The spreadsheet [here](http://vote.minneapolismn.gov/www/groups/public/@clerk/documents/webcontent/wcms1p-126724.xlsx) contains data on the Minneapolis 2013 election by ward and precinct.  Identify the elements of this spreadsheet that are not in standard rectangular data format.
   
<!-- 
    c. **Activity**: Enter data [in this spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0Am13enSalO74dFRFZHNlaVE3NjZfUjBQOUNoMmRlUWc&usp=sharing)
    indicating types of data you are interested in.
-->

 7. Homework: Think about your project (and add into the following [Google Doc](https://docs.google.com/document/d/1ScLIjBWD12P28WbluL6L5Shzh0mLL2V1N9Zm0Z1ljj8/edit?usp=sharing)) [Nick]

### Tuesday
 
1. Project check-in
    b. sharing ideas and one-on-ones [Nick] 
    a. update the Google Doc
 
2. More graphics in R with `ggformula` [Randy and Danny]
 
    a. The graphics-data interface 
        * graphing concepts: [slides](Learn/VizConcepts/VizConcepts.html) [Danny]
        * **Activity:** data <-> graphs [Danny]
        * Eye Training: 
        [[case studies]](https://dtkaplan.github.io/comp110/Presentations/333-eye-training-for-graphics.html)
      
    b. Expanding the `ggformula` toolkit [Randy]
    
        * more types of marks
        * multiple layers
        * scales and guides
        * labeling, themes, etc.
        * data requirements
        * [Plotting with Formulas](http://dtkaplan.shinyapps.io/Plotting_with_formulas)
        * [Refining your plots](https://dtkaplan.shinyapps.io/Refining_ggformula/)
        
    c. Brief Intro to `ggplot2` [Randy]

        * [slides](Learn/ggplot2/ggplot2Intro.pdf) 
        * [Dope Sheets](Learn/ggplot2/ggplot2DopeSheets.pdf) 

 4. R parts of speech and "Chaining Syntax" [Danny]
    a. [slides](Learn/Parts_of_speech/R-command-structure.html)
    b. [exercise](https://dtkaplan.shinyapps.io/part-of-speech-quiz/)
 
 5. Working with data -- 5 verbs of `dplyr` [Nick]    
    a. Goal: Get your data into the right shape for graphing or analysis
 
    b. [slides](Learn/Wrangling/dplyr-intro.html) for presentation;
    
    c. tutorials  
        * [dplyr-movies-tutorial.Rmd](https://rawgit.com/dtkaplan/CVC/gh-pages/Summer2017/Learn/Wrangling/dplyr-movies-tutorial.Rmd) tutorial
        * [dplyr-babynames.Rmd](https://rawgit.com/dtkaplan/CVC/gh-pages/Summer2017/Learn/Wrangling/dplyr-babynames.Rmd) tutorial
    
    d. Building precursors to data wrangling: https://arxiv.org/abs/1401.3269
    
    e. Useful online resource: downloadable chapter on data wrangling from http://mdsr-book.github.io/
 
### Wednesday
 
 1. More data wrangling with `dplyr` and `tidyr` 
 
 <!--
    a. merging data from multiple sources [Danny]
        * [Slides](Learn/Join/joins.html) 
        * [bird-species spreadsheet](https://docs.google.com/spreadsheets/d/1GDKeulVSRXL7Q_5Q0a7Offc_IPX2T4sZ80VN5VLASew/edit#gid=0), 
        * zebrafish treatment [CSV file](Learn/Wrangling/FishTx.csv) 
    b. `gather()`, `spread()`, `separate()` [Randy]
        * [Notes](Learn/TidyData/TidyGapMinder.html)
    c. Building precursors [paper](http://www.amherst.edu/~nhorton/precursors)
-->
    
 2. Ingesting your own data and next steps for your project
 
 3. Teasers
 
    a. Shiny [Example 1 ](https://r.amherst.edu/apps/nhorton/sat);
[Shiny resources](http://shiny.rstudio.com) [Nick]
 
    b. GitHub [Randy]
    
    d. Leaflets [Nick]
 
 4. Welcome to 2nd-half participants
 
 5. Optional Tutorials, TBD
 
### Thursday

 1. Opening (quick) interludes

    a. Brief status reports
    b. Using `dplyr` with an SQL data base 
      * [SQL in R pdf](Learn/SQL/sql-example.pdf)
      * [SQL in R Rmd](https://rawgit.com/dtkaplan/CVC/gh-pages/Summer2017/Learn/SQL/sql-example.Rmd)
    c. Making data available to others (esp. students) via the web. [Notes](Learn/WorkingWithStudents/Providing_files_to_students.html)
    d. Writing functions in R
      * Tom, Dick, and Harry [[html](Learn/WritingFunctions/TomDickAndHarry.html), 
      [Rmd](Learn/WritingFunctions/TomDickAndHarry.Rmd)]
      * How to Write Functions [[html](Learn/WritingFunctions/HowToWriteFunctions.html),
      [Rmd](Learn/WritingFunctions/HowToWriteFunctions.Rmd)]
    e. Googlesheets [Randy or Danny]

 2. Working on projects
 
 3. Optional Tutorials, TBD
 

### Friday

 1. Please fill out the  [Project Report Form](http://goo.gl/forms/14rB29jmVrxw1Ftl2)
 
 2. Live Project Reports (in parallel)

 3. Closing thoughts and goodbyes (finish at 3:00pm)

### Things we did this week

 
<!--
 3. Finding R packages and documentation [Nick]
-->
  
### Additional Topics TBD

In the second half of the workshop, we will offer optional tutorials on topics of 
interest to several workshop participants.   Here are some potential topics, but 
don't be afraid to suggest others. If there is a name listed by a topic, talk to
that person to find out more.

1. Github [Randy]
2. learnr [Danny]
3. Shiny [Miles] --- [Notes](Learn/Shiny-breakout/readme.html)
4. Leaflets, Maps [Leaflets]
5. Machine learning [Danny]
6. Text mining [Nick]
7. Modeling in R [Nick]
8. Writing Functions [Randy]
9. More `ggplot2` [Randy]
10. `ggvis` [Nick]
11. ggplotly [Randy or Danny]
12. Animated GIFs [Miles]
13. Data Scraping from the Web [Miles or Danny]
14. Getting data from a database [Nick]
16. Resampling [Nick]
17. Basic Statistical Methods
18. Linear models with "Less Volume, More Creativity" [Nick]
19. Creating R packages [Randy]
20. R with LaTeX (similar to RMarkdown)
21. Other topics as the arise 
 
### Thanks

* HHMI support
