```{r include=FALSE}
options(markdown.HTML.stylesheet = '../stylesheets/cvc2013.css')
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="../javascripts/main.js"></script>


Working Schedule, June 12-14, 2013 
========================================================

### Resources

* Data and Computing Fundamentals [spring 2013 course syllabus](http://htmlpreview.github.io/?https://github.com/dtkaplan/DataAndComputingFundamentals/blob/master/Spring2013/syllabus2013.html)
* [RStudio server](http://dahl.calvin.edu)
* Slides and files for sessions will be posted in the schedule as we go along

### Provide Feedback
* Give a suggestion/correction: [Google Doc](https://docs.google.com/document/d/1eEwaMvxahJJ2YuFFWgUEmgBj58umwvMwf_GXnsp9Yc0/edit?usp=sharing)  
* Share/send some code via Firepad:  [Alpha](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-alpharIwB7uaxo82e5QET), [Bravo](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-bravoIwB7uaxo82e5QET), [Charlie](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-charlieIwB7uaxo82e5QET), [Delta](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-deltaIwB7uaxo82e5QET), [Echo](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-echoIwB7uaxo82e5QET), [Foxtrot](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-foxtrotIwB7uaxo82e5QET), [Golf](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-golfIwB7uaxo82e5QET), [Hotel](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-hotelIwB7uaxo82e5QET).  




--------------------------

## Wednesday, June 12, 2013

**Noon-1:00: Opening lunch** at Prince Conference Center, Introductions

*Sessions will take place in <strong>Building 128</strong>, refreshments will be in the adjoining 
Reading Room.  Times of sessions are an approximation and will be adjusted as necessary.*

**1:15-3:00: Session 1**, Data and Display Travelogue 

Our colleagues from Macalester will take us on a highlight tour of the types of data sets
and graphical display methodologies used in their one-hour intro course for science students.

* [Welcome](Session1/Welcome.html)
* [Data and Display Travelogue](Session1/DCF-Travelogue/DCF-Travelogue.html)

**3:00-3:15: Coffee break**

**3:15-5:00: Session 2**, RStudio Test Drive

Now it's your turn.  By the end of this session, each participant will have created a simple R Markdown (.Rmd and .Rpres) document in RStudio.  To get you ready, we'll take you on a guided tour
of the main components of RStudio and show how to do some basic things with data (load it in, take a quick look at its structure, make a numerical or graphical summary, etc.)


* [Less Volume, More Creativity](Session2/LearningTeachingR.html)
* Cases and Variables [Rmd file](https://raw.github.com/dtkaplan/CVC/gh-pages/Summer2013/Session2/Cases-And-Variables.Rmd).  Copy this into an editing tab in RStudio.
* [installing `mosaic` and `DCF` locally](Session2/packages.html)


**5:00-5:45: Open Work Time**

*We will end each day with open work time.  This will be mostly unstructured time for you to
ask questions or work on individual projects.*

Don't head to dinner tonight until you have identified a discipline-specific dataset or 
example question as the focus of your slide presentation tomorrow (session 5).  Once you
have determined your topic, you can begin working on that or you can get some additional
practice with RStudio.

**6:00-7:00: Dinner** at Prince Conference Center

**After**: Relax, walk in the Nature Preserve, join others at a pub nearby, etc.

## Thursday, June 13, 2013

**8:30-10:00am: Session 3**, Relational Data

Participants will learn how to create new data sets from existing data sets by grouping, subsetting, and merging and to create graphical outputs  (e.g., scatterplots, maps, etc.) from the resulting data sets.

* [Slides on Relational Operations](Session3/RelationalData.html)
* Crowd-Sourcing [cleaning the bird data](Worksheets/BirdCleaning.html)
* Examples with [maps](Worksheets/FAO-data.html) and [scatter plots](Worksheets/Gapminder-data.html)

**10:00-10:30: Coffee break**

**10:30-Noon: Session 4**, Work on Slides

**Noon-1:00: Lunch**

**1:00-2:00: Session 5a**, Slide Show Part I
Each participant will present 2-4 slides using R Markdown that show an example of a data set or question of interest.

**2:00-2:30: Break/Work/Debriefing**

For those who have not yet presented, this can be a chance to finish up slides -- 
perhaps stealing some ideas from the slide shows  already presented.   It's also a chance to find
out more about the ideas that have been presented.

**2:30-3:30: Session 5b**, Slide Show Part II

The rest of the slide shows.

**3:30-3:45: Coffee break**

**3:45-5:00: Session 6**, Birds of a Feather

This is chance to have follow-up discussions with people interested in similar aspects and/or applications of computation and visualization.  

**5:00-5:45: Open Work Time**

Review and use RStudio to generate graphics or to work on getting data set of interest imported and/or analyzed.

**6:00-7:00: Dinner**

**After**: Relax, walk in the Nature Preserve, join others at a pub nearby, etc.

## Friday, June 14, 2013

**8:30-10:00am: Session 7**, Modeling techniques 

Topics will include notions of best fit, computational tools for computing best fit, confidence intervals for fitted parameters and trees/clustering

**10:00-10:30: Coffee break**

**10:30-Noon: Session 8**, Work Time

Continue working with your data (small-group consulations available)

**Noon-1:00: lunch**

**1:00-3:15: Session 9**, Planning for Next Steps

Discussion to determine

 * tools/recources needed
 * other key players that will help ensure success
 * timeline for implementation
 * possible barriers/challenges for sustaining effort when return to own campus
 * what CVC can do for you
 * how do we teach this to students (which instructors, which methods, which courses)
 

**3:15-3:30: Coffee break**

**3:30-4:30: Wrap-up/depart**

