---
title: "CVC Modeling"
author: "Nicholas Horton"
date: "7/11/2014"
output: pdf_document
---

This is a sample of modeling using mosaic

```{r message=FALSE}
options(digits=3)
require(mosaic)
```


```{r}
favstats(~ female, data=HELPrct)
tally(~ sex, data=HELPrct)
tally(~ sex, format="percent", data=HELPrct)

mean(pcs ~ sex, data=HELPrct)
bwplot(pcs ~ sex, data=HELPrct)
```

Now let's fit a multiple regression model for PCS (physical component scores) that includes mcs, sex, and substance (3 levels).
```{r}
mlrmaineffect <- lm(pcs ~ mcs + sex + substance, data=HELPrct)
coef(mlrmaineffect)
summary(mlrmaineffect)
```

Let's do some model diagnostics.

```{r}
mplot(mlrmaineffect, which=7, xlim=c(-5, 10), ylim=c(1.5, 6))
histogram(~ resid(mlrmaineffect), fit='normal')
```

Let's plot some predicted values, say for a alcohol involved subject, as a function
of being male vs. female and MCS score.
```{r}
mlrmefun = makeFun(mlrmaineffect)
xyplot(pcs ~ mcs, data=HELPrct)
plotFun(mlrmefun(mcs, sex="female", substance="alcohol") ~ mcs, add=TRUE, col="black")
plotFun(mlrmefun(mcs, sex="male", substance="alcohol") ~ mcs, add=TRUE, col="red")
```

But for something even more amazing...

```{r}
danny1 = lm(diabetic ~ age + bmi, data=NHANES)
dan1fun = makeFun(danny1)
plotFun(dan1fun(age=age, bmi=bmi) ~ age + bmi, xlim=c(0, 80), ylim=c(15, 40))
```

```{r}
danny2 = lm(diabetic ~ age + bmi + age*bmi, data=NHANES)
dan2fun = makeFun(danny2)
plotFun(dan2fun(age=age, bmi=bmi) ~ age + bmi, xlim=c(0, 80), ylim=c(15, 40),
        main="Difference in predicted probabilities of diabetes (Interaction Model)")
```

```{r}
densityplot(~ resid(danny1) + resid(danny2))
```


Contour plots...

```{r}
plotFun((dan2fun(age=age, bmi=bmi) - dan1fun(age=age, bmi=bmi)) ~ age + bmi, xlim=c(0, 80), ylim=c(15, 40), main="Difference in predicted probabilities\nof diabetes (Interaction - Main Effect)")
```

```{r}
smallNHANES = sample(NHANES, 500)
```



