---
title: "Working Schedule"

output: 
  html_document:
    template: null
    css: ../stylesheets/cvc.css
---


<script src="../javascripts/main.js"></script>
<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

<div class="wrapper">
<nav>
<ul></ul>
</nav>
<section>
     
           
<header>
<h1>2018 Computation and Visualization Workshop</h1>
<p>Grinnell College</p>
</header> 

This is cvc.mosaic-web.org/Summer2018/schedule2018.html

## Resources

  * [CRAN](http://cran.r-project.org) (Comprehensive R Archive Network) has lots of R-related stuff
  * The `mosaic` package and its vignettes are [available via CRAN](http://cran.r-project.org/web/packages/mosaic/index.html) and also via [github](https://github.com/ProjectMOSAIC/mosaic)
  * The `ggformula` package and its vignettes are [available via CRAN](http://cran.r-project.org/web/packages/ggformula/index.html) and also via [github](https://github.com/ProjectMOSAIC/ggformula)
  * [R Studio Cheatsheets](https://www.rstudio.com/resources/cheatsheets/) are very useful.
<!-- * [The Calvin College RStudio server](http://rstudio.calvin.edu) has provided accounts for all workshop participants. -->
<!-- * [Change passwords here](https://freeipa1.cs.calvin.edu/) -->
  * Slides and files for sessions will be posted in the schedule as we go along (see below).


## Provide Feedback

We'll use this Google Doc to record your questions and comments and to provide
responses.  Feel free to edit it at anytime before, during, or (shortly) after the workshop.

  * [Google Doc](https://docs.google.com/document/d/1t3jlDOpXnv1YI-GiekWPiRXR5CsHlNn5B851W5fSgBY/edit?usp=sharing)

## Project ideas and updates

We'll use this Google Doc to share information about project ideas and updates.

  * [Google Doc]()

## Working Schedule

This schedule will be updated throughout the workshop.  All items should be 
considered tentative until they happen since we will adjust things to 
meet the needs and wishes of the participants.

### Sunday

Arrival day for many coming from out of town. 

### Monday

 0. Arrival and Breakfast (8:00)
 
 1. Welcome (9:30am)
    a. Welcome to CVW/Grinnell
    b. [Goals and outline for the workshop](Intro/IntroOverview.html) [Randy]

 2. Introductions [Randy]
     
    * [Google Doc](https://docs.google.com/document/d/1lDt3NsoFML1TaosPjaDjrlKFtFtxMYKMEtPvMmuXjG0/edit?usp=sharing)

 3. Example Case Studies: 
 
    * [Medicare Data]()
    * [What's Normal?]()
    * 
    
 4. Ingredients List
 
    * Graphics (`ggformula`)
    * Tidy Data and Data Wrangling (`dplyr`, `tidyr`, etc.)
    * Data scraping (`rvest`)
    * Importing your own data (`readr`, `googlesheets`, `readxl`)
    * Tutorials -- run R code in a webpage (`learnr`)
    * Reporting (`rmarkdown`, `bookdown`, `blogdown`, `knitr`, `flexdashboard`, etc.)
    * Apps -- interactivity, but no code (`shiny`, shinydocs)
    * Maps -- `leaflet`
    * Websites -- rstudio.cloud + GitHub
    * GitHub
    
 5. Less Volume, More Creativity [Randy]
 
    * A general approach to using R
    
    * Introduction to `ggformula` for graphics
    
  6. Using RStudio.cloud [Danny]

<table>
<tr>
<th width = "50%">
Track A [Danny]
</th>
<th width = "50%">
Track B [Randy]
</th>
</tr>
<tr valign = "top">
<td valign = "top">
 7. More Orientation to RStudio 
 
 8. How to organize your data
    
    a. [**Introduction slides**](Learn/TidyData/tidy_data.html), but the basics are
    
      * Rectangular format: cases (rows) and variables (columns)
      * Separate your analysis from data storage.
      * Use a codebook to describe your cases and variables in detail.
      
    b. `tidyverse` provides a toolkit for getting data into
    this format.  (More later.)
    
 9. Importing CSV and Excel files into RStudio
 
      * [Notes](Learn/ImportingData/ImportingData.html)
      * [Anscombe.csv](Learn/ImportingData/Anscombe.csv)
    
 10. [RMarkdown](http://prezi.com/vq6l5yqpnqma/) 
    a. [TISE paper by Baumer *et al*](http://escholarship.org/uc/item/90b2f5xh)
    
    b. [RMarkdown cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)

<!-- 
        b. **Activity**: The spreadsheet [here](http://vote.minneapolismn.gov/www/groups/public/@clerk/documents/webcontent/wcms1p-126724.xlsx) contains data on the Minneapolis 2013 election by ward and precinct.  Identify the elements of this spreadsheet that are not in standard rectangular data format. 
-->

<!-- 
    c. **Activity**: Enter data [in this spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0Am13enSalO74dFRFZHNlaVE3NjZfUjBQOUNoMmRlUWc&usp=sharing)
    indicating types of data you are interested in.
-->
</td>
<td valign = "top">
7. [RMarkdown](http://prezi.com/vq6l5yqpnqma/) [?]

    a. [TISE paper by Baumer *et al*](http://escholarship.org/uc/item/90b2f5xh)
    
    b. [RMarkdown cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
    
8. Working with data -- 5 verbs of `dplyr`
 
    a. Goal: Get your data into the right shape for graphing or analysis
 
    b. [Tutorial](http://rsconnect.calvin.edu/tidyverse-city-of-hope)
    
    c. Building precursors to data wrangling: https://arxiv.org/abs/1401.3269
    
    d. Useful online resource: downloadable chapter on data wrangling from http://mdsr-book.github.io/
    
9. Customization with `ggformula` [?]
</td>
</tr>
</table>

### Tuesday
 
1. Project check-in
 
<!-- 2. More graphics in R with `ggformula` [Randy and Danny] -->

<!--     a. The graphics-data interface  -->
<!--         * graphing concepts: [slides](Learn/VizConcepts/VizConcepts.html) [Danny] -->
<!--         * **Activity:** data <-> graphs [Danny] -->
<!--         * Eye Training:  -->
<!--         [[case studies]](https://dtkaplan.github.io/comp110/Presentations/333-eye-training-for-graphics.html) -->

<!--     b. Expanding the `ggformula` toolkit [Randy] -->

<!--         * more types of marks -->
<!--         * multiple layers -->
<!--         * scales and guides -->
<!--         * labeling, themes, etc. -->
<!--         * data requirements -->
<!--         * [Plotting with Formulas](http://dtkaplan.shinyapps.io/Plotting_with_formulas) -->
<!--         * [Refining your plots](https://dtkaplan.shinyapps.io/Refining_ggformula/) -->

<!--     c. (Optional) Brief Intro to `ggplot2` -->

<!--         * [slides](Learn/ggplot2/ggplot2Intro.pdf)  -->
<!--         * [Dope Sheets](Learn/ggplot2/ggplot2DopeSheets.pdf)  -->

<!--  4. R parts of speech and "Chaining Syntax" [Danny] -->
<!--     a. [slides](Learn/Parts_of_speech/R-command-structure.html) -->
<!--     b. [exercise](https://dtkaplan.shinyapps.io/part-of-speech-quiz/) -->

<table> 
<tr>
<th width = "50%">
Track A [Randy]
</th>
<th width = "50%">
Track B [Danny]
</th>
</tr>
<tr valign = "top">
<td valign = "top">
 2. Working with data -- 5 verbs of `dplyr`
 
    a. Goal: Get your data into the right shape for graphing or analysis
 
    b. [Tutorial](http://rsconnect.calvin.edu/tidyverse-city-of-hope)
    
    c. Building precursors to data wrangling: https://arxiv.org/abs/1401.3269
    
    d. Useful online resource: downloadable chapter on data wrangling from http://mdsr-book.github.io/
    
</td>
<td>
Topics TBD
</td>
</tr>
</table>
 
### Wednesday
 
 <!-- 1. More data wrangling with `dplyr` and `tidyr` [Randy]  -->

 <!--    a. `spread()`, `gather()`, joins, etc. -->

 <!--    b. A data tidying case study: [tidydata-TB-tutorial.Rmd](https://rawgit.com/dtkaplan/CVC/gh-pages/Summer2017/Learn/Wrangling/tidydata-TB-tutorial.Rmd) -->

 <!--
    a. merging data from multiple sources [Danny]
        * [Slides](Learn/Join/joins.html) 
        * [bird-species spreadsheet](https://docs.google.com/spreadsheets/d/1GDKeulVSRXL7Q_5Q0a7Offc_IPX2T4sZ80VN5VLASew/edit#gid=0), 
        * zebrafish treatment [CSV file](Learn/Wrangling/FishTx.csv) 
    b. `gather()`, `spread()`, `separate()` [Randy]
        * [Notes](Learn/TidyData/TidyGapMinder.html)
    c. Building precursors [paper](http://www.amherst.edu/~nhorton/precursors)
-->
    
<!--  2. Ingesting your own data and next steps for your project -->

<!--  3. Teasers -->

<!--     a. Shiny [Example 1 ](https://r.amherst.edu/apps/nhorton/sat); -->
<!-- [Shiny resources](http://shiny.rstudio.com) [Nick] -->

<!--     b. GitHub [Randy] -->

<!--     c. learnr (with hints and checked answers and bells and whistles, see https://rstudio.github.io/learnr and https://rstudio.github.io/learnr/exercises.html#hints-and-solutions) [Danny] -->

<!--     d. Leaflets ([leaflet.Rmd](https://rawgit.com/dtkaplan/CVC/gh-pages/Summer2017/Learn/Leaflets-breakout/Leaflet_notes.Rmd), see also https://rstudio.github.io/leaflet) [Nick] -->

<!--  4. Welcome to 2nd-half participants -->

<!--  5. Optional Tutorials      -->
<!--      - Learnr tutorials [the rmd document we developed](Projects/testing_tea/testing_tea/testing_tea.Rmd) -->

<!-- ### Thursday -->

<!--  1. Opening (quick) interludes -->

<!--     a. Brief status reports -->
<!--     b. Using `dplyr` with an SQL data base  -->
<!--       * [SQL in R pdf](Learn/SQL/sql-example.pdf) -->
<!--       * [SQL in R Rmd](https://rawgit.com/dtkaplan/CVC/gh-pages/Summer2017/Learn/SQL/sql-example.Rmd) -->
<!--     <!-- c. Making data available to others (esp. students) via the web. [Notes](Learn/WorkingWithStudents/Providing_files_to_students.html) --> -->
<!--     c. Simple text mining for fun and profit -->
<!--       * [text.html](Learn/Text/text.html) -->
<!--       * [text.Rmd](https://rawgit.com/dtkaplan/CVC/gh-pages/Summer2017/Learn/Text/text.Rmd) -->
<!--     d. Writing functions in R -->
<!--       * Tom, Dick, and Harry [[html](../Summer2016/Learn/WritingFunctions/TomDickAndHarry.html),  -->
<!--       [Rmd](../Summer2016/Learn/WritingFunctions/TomDickAndHarry.Rmd)] -->
<!--       * How to Write Functions Tutorial [[Rmd](https://rawgit.com/dtkaplan/CVC/gh-pages/Summer2017/Learn/WritingFunctions/HowToWriteFuctions-Tutorial/HowToWriteFunctions.Rmd), [Live Tutorial](http://rstudio.calvin.edu:3939/writing-functions/)] -->
<!--     e. Googlesheets [Randy or Danny] -->

<!--  2. Working on projects -->

<!--  3. Optional Tutorials, TBD -->

<!--    a. Using Github and Making Packages -->
<!--       * [Hadley's advice on making packages with modern tools](http://r-pkgs.had.co.nz/) -->
<!--       * [learn git branching](http://learngitbranching.js.org/) -->
<!--       * data at [http://www.calvin.edu/~rpruim/data/HIVdata.csv](http://www.calvin.edu/~rpruim/data/HIVdata.csv) -->

<!-- ### Friday -->

<!--  1. Please fill out the  [Project Report Form](http://goo.gl/forms/14rB29jmVrxw1Ftl2) -->

<!--  2. How to make a website (GitHub edition) -->
<!--    * [Notes](https://dtkaplan.github.io/MakingAWebSite/) -->
<!--    * You can post tutorials at [http://shinyapps.io](http://shinyapps.io) or at -->
<!--    [http://rstudio.calvin.edu:3939](http://rstudio.calvin.edu:3939) -->

<!--  3. Break out sessions -->
<!--     a. Shiny -->
<!--        * [slides from a shiny workshop at Big Data Ignite 2016](http://rpruim.github.io/talks/bigdataignite2016/shiny/04-Shiny.pdf) -->
<!--     b. Web scraping -->
<!--     c. Machine Learning -->
<!--       * [Notes](Learn/MachineLearning/MachineLearning.html) -->
<!--     d. Modeling in R -->
<!--       * [Transcript of Break out](Learn/Modeling/Modeling2.html) -->
<!--       * [PDF from 2016](Learn/Modeling/Modeling.pdf) -->

<!--  4. Project Reports -->

<!--  5. Closing thoughts and good-byes -->

## Example Projects from 2017 Workshop

Here is a sampler of things people worked on during their "project time" in 2017.
 
 * USC Dornsife/LA Times Daybreak Election Poll
    * data available online
    * time series of overall trends Clinton vs Trump
    * to do: add in covariates from the data
    
 * Tutorials for lower division Science courses to show how stats can be used there
    * Chem, Bio, Env Science
    
 * Wrangle data for a longitudinal study
 
 * Animation of seismic waves passing through the US (Earth scope data)
    * ggmap for mapping
    * ffmpeg to stich stills into movie
    
  * Earthquake epicenter mapper with additional data overlays
  
  * Tutorial for intro stats class 
    * learned to think about goals and flow of tutorial
    * first week of class tutorial -- "run and adjust"
    
  * Migrating from SAS to R
    * love graphics in R
    * hoping to move more and more analyses to R
    
  * Bike share data in DC & Twin Cities
    * visualzation of usage over time (and season)
    
  * [HMP Explorer](http://rstudio.calvin.edu:3939/connect/#/apps/4/access)
     * Human Microbiome data
     
  * Two shiny apps
    * Coin Flipping simulations
    * Goodness of Fit Test 
    
  * Maps using R
  
  * Learn to make tutorials with 
    * mathematical formulas
    * visualization of t-test
    * solution code
    * sliders to adjust plots and other output
    * exercises/quizzes
    
  * Visualiztion of Interlibrary Load data
    
  * Make better connections between Inro Biostats and Bio Course
    * data wrangling for data that will be used
    * shiny app with repository of example analyses
    
  * Working with data from CDC survey on behavior risk
  
## Additional Topics TBD

Here are some potential topics, but don't be afraid to suggest others. If there
is a name listed by a topic, talk to that person to find out more.

1. Github [Randy]
2. learnr tutorials [Randy]
3. Shiny [Danny]
4. Leaflets, Maps [Danny]
5. Machine learning 
6. Text mining 
7. Modeling in R 
8. Writing Functions [Randy]
9. `ggplot2` [Randy]
10. `ggplotly` 
11. Data Scraping from the Web
12. Getting data from a database
13. Resampling 
14. Creating R packages [Randy]
15. R with LaTeX (similar to RMarkdown)
16. Other topics as they arise 
 
### Thanks

* Host Institution: Grinnell
* Previous Workshops supported by HHMI and the Computation and Visualization Consortium

