---
title: "Working Schedule"

output: 
  html_document:
    template: null
    css: ../stylesheets/cvc.css
    
---


<script src="../javascripts/main.js"></script>
<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

<div class="wrapper">
<nav>
<ul></ul>
</nav>
<section>
     
           
<header>
<h1>CVC 2016 Working Schedule</h1>
<p>Computation and Visualization Consortium</p>
</header> 


## Resources

  * [CRAN](http://cran.r-project.org) (Comprehensive R Archive Network) has lots of R-related stuff
  * The `mosaic` package (version 0.13 or greater) and its vignettes are [available via CRAN](http://cran.r-project.org/web/packages/mosaic/index.html) and also via [github](https://github.com/ProjectMOSAIC/mosaic)
  * [The Calvin College RStudio server](http://rstudio.calvin.edu) has provided accounts for all workshop participants.
    * [Change passwords here](https://freeipa1.cs.calvin.edu/)
  * Slides and files for sessions will be posted in the schedule as we go along (see below).


## Provide Feedback

We'll use this Google Doc to record your questions and comments and to provide
responses.  Feel free to edit it at anytime before, during, or (shortly) after the workshop.

  * [Google Doc](https://docs.google.com/document/d/1AtoWauyDoBsHJd7yywkJNgiNaAXPiBjNhqO9Yw72jys/edit?usp=sharing)

## Working Schedule

This schedule will be updated throughout the workshop.  All items should be 
considered tentative until they happen since we will adjust things to 
meet the needs and wishes of the participants.

### Sunday

Arrival day for many coming from out of town. 

**Opening reception**, 5 pm - 7 pm at Jo Hardin's house
 
  * Check your email for details.

### Monday

 1. Welcome (9am)
    a. Welcome to CVC/Pomona [Jo]
    b. [Goals and outline for the week](Intro/IntroOverview.html) [Randy]

 2. Introductions [Randy]
    a. **Activity**: Split up into groups of three or four and introduce yourselves. 
    b. [Google Doc](https://docs.google.com/document/d/137aTs2EEcBdE7hg1tH68wjsorqSNdcB8VnZQmUX-VCs/edit?usp=sharing) for second part. 

 3. A First Case Study using Medicare Data [Danny]

    * [Slides](Intro/MedicareSpending.html)

 4. Introduction to R and R Studio [Randy]

    * [Less Volume, More Creativity -- An R Quick Start](Learn/LessVolume/LessVolume.html) 
    * Importing CSV and Excel files into RStudio
        * [Notes](Learn/ImportingData/ImportingData.html)
        * [Anscombe.csv](Learn/ImportingData/Anscombe.csv)
    
    * **Activity**: Create a plot using data that you have imported into R.

 5. [RMarkdown](http://prezi.com/vq6l5yqpnqma/) [Nick]
 
    * Creating PDF/HTML/Word documents in RStudio
    * [TISE paper by Baumer *et al*](http://escholarship.org/uc/item/90b2f5xh)
    c. **Activity**: Write and publish a description of some 
    straightforward, data-oriented topic you'd like to present in class. 
        * Include at least 1 plot (even if unrelated) to make sure 
        you know how to do that.  
        * Use the mosaic `plain` html template as a starting point
        
 6. How to organize your data [Danny]
    
    a. [Introduction slides](Learn/TidyData/tidy_data.html), but the basics are
    
    * Rectangular format: cases (rows) and variables (columns)
    * Separate analysis from data storage.
    * use a codebook to describe your cases and variables in detail
       
    b. **Activity**: The spreadsheet [here](http://vote.minneapolismn.gov/www/groups/public/@clerk/documents/webcontent/wcms1p-126724.xlsx) contains data on the Minneapolis 2013 election by ward and precinct.  Identify the elements of this spreadsheet that are not in standard rectangular data format.
   
<!-- 
    c. **Activity**: Enter data [in this spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0Am13enSalO74dFRFZHNlaVE3NjZfUjBQOUNoMmRlUWc&usp=sharing)
    indicating types of data you are interested in.
-->

 7. Project Example -- Dynamic Data [Jo]    
 
     a. [slides](Learn/ProjectExamples/DynDataCVC.html) for presentation; 
        [markdown file](Learn/ProjectExamples/DynDataCVC.Rmd) also available  
     b. [manuscript](http://arxiv.org/abs/1603.04912) on arXiv  
     c. [complete example markdown files](http://research.pomona.edu/johardin/papers-and-publications/) also available

### Tuesday
 
 1. Project check-in: sharing ideas and one-on-ones
 
 2. The graphics-data interface 
    a. graphing concepts: [slides](Learn/VizConcepts/VizConcepts.html) [Randy/Danny]
    b. **Activity:** data <-> graphs [Danny]
    PDF with [the graphs](Learn/VizConcepts/Exercise/graphics_for_grammar.pdf) & the [questions](Learn/VizConcepts/Exercise/graphics_questions.pdf)
    
 3. Introduction to `ggplot2` --  turning the concepts into pictures with the grammar of graphics

    a. [slides](Learn/ggplot2/ggplot2Intro.pdf) 
<!-- 
    b. [Dope Sheets](Learn/ggplot2/DopeSheets.pdf) 
-->

 4. Working with data -- 5 verbs of `dplyr` [Jo]    
    Getting your data into the right shape for graphing or analysis
 
     a. [slides](Learn/Wrangling/dplyrCVC.html) for presentation; 
        [markdown file](Learn/Wrangling/dplyrCVC.Rmd) also available
 
     b. [Worksheet](Learn/Wrangling/dplyrwrkshtCVC.html) for presentation; 
       [markdown file](Learn/Wrangling/dplyrwrkshtCVC.Rmd) also available (and on the Calvin server)
  
 5. Getting your own data into R [Randy]

<!-- 
    a. [Notes](Learn/ImportingData/ImportingData.html)
    b. [Anscombe.csv](Learn/ImportingData/Anscombe.csv)
    c. [Gender.xls](Learn/ImportingData/Gender.xls)
    d. a DataCamp [tutorial](http://blog.datacamp.com/r-data-import-tutorial/)
-->
 
### Wednesday
 
 1. More data wrangling with `dplyr` and `tidyr` 
 
 <!--
    a. merging data from multiple sources [Danny]
        * [Slides](Learn/Join/joins.html) 
        * [bird-species spreadsheet](https://docs.google.com/spreadsheets/d/1GDKeulVSRXL7Q_5Q0a7Offc_IPX2T4sZ80VN5VLASew/edit#gid=0), 
        * zebrafish treatment [CSV file](Learn/Wrangling/FishTx.csv) 
    b. `gather()`, `spread()`, `separate()` [Randy]
        * [Notes](Learn/TidyData/TidyGapMinder.html)
    c. Building precursors [paper](http://www.amherst.edu/~nhorton/precursors)
-->
    
 2. Quick Shiny intro [Example](https://r.amherst.edu/apps/nhorton/sat/) 
 
 3. Ingesting your own data and starting on your project
 
 4. Optional Tutorials TBA
 
 5. 4 pm:  Seminar with Hilary Parker (from [Stitch Fix](http://multithreaded.stitchfix.com/blog/) and [Not So Standard Deviations](https://soundcloud.com/nssd-podcast) )

### Thursday

 1. Working on projects
 
 2. Optional Tutorials TBA
 
 3. Dinner at [Buca di Beppo](http://www.bucadibeppo.com/restaurants/ca/claremont/)


### Friday

 1. Please fill out the  [Project Report Form]()
 
 2. Live Project Reports

<!--
 3. Finding R packages and documentation [Nick]
-->
  
### Additional Topics TBD

In the second half of the workshop, we will offer optional tutorials on topics of 
interest to several workshop participants.   Here are some potential topics, but 
don't be afraid to suggest others. If there is a name listed by a topic, talk to
that person to find out more.

1. Github [Randy]
3. Shiny [Danny, Nick, or Jo]
4. Leaflets, etc. [Danny]
5. Maps [Danny]
5. Machine learning [Danny]
6. Text mining [Nick]
7. Modeling in R [Nick]
8. Writing Functions [Randy]
9. More `ggplot2` [Randy]
10. `ggvis` [Nick or Randy]
11. Data Scraping from the Web
1. Getting data from a database
12. Image Analysis
13. Resampling [Nick]
10. Basic Statistical Methods
15. Linear models with "Less Volume, More Creativity" [Nick or Jo]
16. Other topics as the arise 
 
