---
title: "Working Schedule"

output: 
  html_document:
    template: null
    css: ../stylesheets/cvc.css
    
---


<script src="../javascripts/main.js"></script>
<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

<div class="wrapper">
<nav>
<ul></ul>
</nav>
<section>
     
           
<header>
<h1>CVC 2015</h1>
<p>Computation and Visualization Consortium</p>
</header> 

# Resources and Working Schedule

## Resources

  * [CRAN](http://cran.r-project.org) (Comprehensive R Archive Network) has lots of R-related stuff
  * The `mosaic` package (version 0.10 or greater) and its vignettes are [available via CRAN](http://cran.r-project.org/web/packages/mosaic/index.html) and also via [github](https://github.com/ProjectMOSAIC/mosaic)
  * [The Calvin College RStudio server](http://rstudio.calvin.edu:8787) has provided accounts for all workshop participants.
Teaching Statistics Using R.
  * Slides and files for sessions will be posted in the schedule as we go along (see below).
  * The [CVC 2015 R Pubs site](http://rpubs.com/uscots-2015) can be used
  to post documents for others to see.



## Provide Feedback

We'll use this Google Doc to record your questions and comments and to provide
responses.  Feel free to edit it at anytime before, during, or (shortly) after the workshop.

  * [Google Doc](https://docs.google.com/document/d/1AN1vOgnUF2zM5SNHPW17kdt1BMPGbK0izqXCBWvXj4M/edit?usp=sharing) 

## Working Schedule

This scheule will be updated throughout the workshop.  All items should be 
considered tentative until they happen since we will adjust things to 
meet the needs and wishes of the participants.

### Sunday

Arrival day for many coming from out of town.  

### Monday

 1. Welcome
    a. Welcome to CVC [Ben]
    b. [Goals and outline for the week](Slides/IntroOverview.html) [Randy]

 2. Introductions [Randy]
    a. **Activity**: Split up into groups of three or four and introduce yourselves. 
    b. [Google Doc](https://docs.google.com/document/d/1Zt5AYH7HsXTbIl5d6gjn0E_-e5m59IBmIo0jrIkLXsI/edit?usp=sharing) for second part. 

 3. A First Case Study using Medicare Data [Danny]

    * [Slides](http://dtkaplan.github.io/CVC/Summer2014/Notes/MedicareSpending/PriceOfHealth.html)

 4. Introduction to R and R Studio [Randy]

    * Layout and configuration of RStudio 
    * [Less Volume, More Creativity -- An R Quick Start](Slides/LessVolume.html) 
    * Importing CSV files
        * [Notes](Learn/ImportingData/ImportingData.html)
        * [Anscombe.csv](Learn/ImportingData/Anscombe.csv)
        * [Gender.xls](Learn/ImportingData/Gener.xls)
    
    * **Activity**: Create a plot using data that you have imported into R.

 5. [RMarkdown](http://prezi.com/e7wtfnacj9ub/) [Nick/Ben]
 
    * Creating PDF/HTML/Word documents in RStudio
    * [TISE paper by Baumer *et al*](http://escholarship.org/uc/item/90b2f5xh)
    c. **Activity**: Write and publish a description of some 
    straightforward, data-oriented topic you'd like to present in class. 
        * Include at least 1 plot (even if unrelated) to make sure 
        you know how to do that.  
        * Bonus: import data from a CSV or some other file.
        
 6. How to organize your data [Danny]
    a. Rectangular format: cases (rows) and variables (columns)

    b. Separate analysis from data storage.
       * don't forget a codebook that describes your cases and variables in detail
       
    c. **Activity**: The spreadsheet [here](http://vote.minneapolismn.gov/www/groups/public/@clerk/documents/webcontent/wcms1p-126724.xlsx) contains data on the Minneapolis 2013 election by ward and precinct.  Identify the elements of this spreadsheet that are not in standard rectangular data format.
    
    d. **Activity**: Enter data [in this spreadsheet](https://docs.google.com/spreadsheet/ccc?key=0Am13enSalO74dFRFZHNlaVE3NjZfUjBQOUNoMmRlUWc&usp=sharing)
    indicating types of data you are interested in.



### Tuesday

 1. Project Reports [Ben]
    a. **Activity**: come prepared to give a (very brief) 
    report on the status of your project idea(s).
 
 2. The graphics-data interface
    a. graphing concepts: [slides](Slides/VizQuickStart.html) [Randy/Danny?]
    b. **Activity:** data <-> graphs [Danny]
    
 3. Introduction to `ggplot2` [slides](Slides/ggplot2Intro.pdf) [Randy]
    a. Turning the concepts into pictures with the grammar of graphics

 4. Working with data -- 5 verbs of `dplyr` [Danny]
    * Getting your data into the right shape for graphing or analysis
    * **Activity**: Baby names [Nick]
    
 5. Getting your own data into R [Randy?]
    a. CSV
    b. Excel
    c. Google
    d. etc.
 
### Wednesday
 
 1. More data wrangling with `dplyr` and `tidyr` [Danny]
    a. `group_by()`
    b. merging data from multiple sources (joining)
    c. `gather()`
    
 2. More `ggplot2` [Randy]
    
 3. Plans for Phase 2
    a. Project Quick Reports
    b. Additional Sessions

### Thursday

### Friday

### Addition Topics TBD

  1. Getting data from a database [Ben?]
  2. Finding R packages and documentation [?]
  3. Github [Randy]
  4. Shiny [Danny?]
  5. Maps [?]
  6. Machine learning [?]
  7. Text mining [?]
  8. Modeling in R [Nick]
  9. Writing functions [Randy]
     * **Activity**: `Birthdays`


