---
title: "CVC 2014 Schedule"
date: "July, 2014"
output: html_document
---

```{r include=FALSE}
options(markdown.HTML.stylesheet = '../stylesheets/cvc2013.css')
options(rstudio.markdownToHTML =
  function(inputFile, outputFile) {     
    require(markdown)
    markdownToHTML(inputFile, outputFile, stylesheet='../stylesheets/cvc2013.css')  
  }
)
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="../javascripts/main.js"></script>


Working Schedule, July 7-11, 2014 
========================================================

### Resources
* `mosaic` package (version 0.9-0 or greater) and its vignettes are [available via CRAN](http://cran.r-project.org/web/packages/mosaic/index.html) and also via [github](https://github.com/rpruim/mosaic)
* [The Calvin College RStudio server](http://acc.calvin.edu) has provided accounts for 
all workshop participants.
* Data and Computing Fundamentals [spring 2013 course syllabus](http://htmlpreview.github.io/?https://github.com/dtkaplan/DataAndComputingFundamentals/blob/master/Spring2013/syllabus2013.html)
* Materials for our [USCOTS 2013 Workshop](http://uscots2013.mosaic-web.org/Workshop) on
Teaching Statistics Using R.
* Slides and files for sessions will be posted in the schedule as we go along

### Provide Feedback
* Give a suggestion/correction: [Google Doc](https://docs.google.com/document/d/1eEwaMvxahJJ2YuFFWgUEmgBj58umwvMwf_GXnsp9Yc0/edit?usp=sharing)  
* Share/send some code via Firepad:  [Alpha](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-alpharIwB7uaxo82e5QET), [Bravo](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-bravoIwB7uaxo82e5QET), [Charlie](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-charlieIwB7uaxo82e5QET), [Delta](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-deltaIwB7uaxo82e5QET), [Echo](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-echoIwB7uaxo82e5QET), [Foxtrot](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-foxtrotIwB7uaxo82e5QET), [Golf](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-golfIwB7uaxo82e5QET), [Hotel](http://www.mosaic-web.org/go/firepad/examples/codeCOMP121.html#-hotelIwB7uaxo82e5QET).  




--------------------------

## Sunday

Arrival and opening dinner

## Monday

1. Welcome and Introductions

#. A First Case Study [Danny]

#. RStudio orientation 1 [Randy]
    a. arithmetic and syntax
    #. getting help
    

#. Less Volume, More Creativity -- An R Quick Start [Randy]
    #. Principles for successfully using R with students
    
    #. The formula-interface template
        * graphical summaries with `lattice`
        * numerical summaries with `mosaic`
        * foreshadowing modeling with `lm()` and its cousins

#. RMarkdown [Nick]
    a. Creating PDF/HTML/Word documents in RStudio
    #. **Activity**: Write and publish a description of some straightforward, data-oriented topic you'd like to present in class.  Keep it simple.  We'll do more complex things in the 2nd half of the workshop.
    
#. Basic R building blocks
    a. basic data types: numeric, character, factor, logical
    #. some special objects: `NA`,  `NaN`, and `NULL`
    #. containers
        * vectors, lists, and data frames
    #. objects and classes
    #. names
        * variable names versus strings
    
#. Data Organization
    a. table/case/variable/row/column
        * Why Common excel formats violate this
    b. importing data from Excel and other files
    #. wide vs narrow formats
        * NCI60 and Aaron's wind matrices

#. The graphics-data interface -- graphing concepts
    a. goal: more flexible creation of customized plots
    
    #. parts of graphics
        * frame, scale, glyph, guide, facet
        * information encoding in glyphs (properties/aesthetics)
    
    #. **Activity:** Graph to data: What data do a I need to make my graph? [Danny]
        * will develop data manipulation tools shortly
    
    #. **Activity:** Data to graph: mapping data to glyphs and their properities/aesthetics [Danny]
    
    #. Make a 6-second Vine video about graphics, like [this one](https://vine.co/v/MI5DM173wWz) and [this one](https://vine.co/v/MI5EWixM65A) about glyphs.
    
#. Important data operations:
    a. `mosaic` utilities using the formula-interface
    #. `dplyr` toolkit (`mutate()`, `filter()`, `select()`, `summarize()`, `arrange()`, 
        and `group_by()`
    #. merging data from multiple sources
    #. normalization (use Medicare spending case study)
        
    
#. Introducing `ggplot`
    #. Other geoms with other data sets
    #. `mplot()` 
    #. `ggplot` examples with barchart
    
    
#. The idea of a backstory
    a. Show sort of data that underlies the dynamite plot
    #. Something that involves a join.
#. `summarize()`
#. `mutate()` and common sorts of operations
    #. ratios, rates
    #. ???
#. `filter()`
#. `group_by()` these operations (using groupwise properties)


#. Report on your mini-case (first 6 people or groups @ 5 minutes)

## Tuesday

1. Sources of data, and how to get it in to R
    #. Files, URLs, CSV, Workspaces, 
    #. From Excel
    #. Databases.  Example from Randy about FAA Flights: <http://www.calvin.edu/~rpruim/talks/LessVolume/2014-05-29-GreatPlainsRUsers/dplyrLessVolume.html>
#. Identifying sources of data from your mini-case study
    #. Work in groups?  
#. Join operation
    
#. Report on your mini-case (second 6 people or groups @ 5 minutes)

## Wednesday 

### Morning

### Afternoon


## Thursday

## Friday 


## Notes

The first 2.5 days includes:

* an introduction to using R for handling data and graphics
* deconstructing graphs to the underlying data
* constructing graphics from data
* data wrangling: operations to get data in the right form for graphics

The second 2.5 days includes:

* quick review of the first half of workshop
* one-on-one or small group (by discipline) development of case studies.
* summarizing data with models
* data cleaning
* data web-scraping basics 
* programming in R (as needed)

